apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-logs-local-path-pvc
  namespace: quantal-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2G

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-local-path-pvc
  namespace: quantal-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2G

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-local-path-pvc
  namespace: quantal-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2G