apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantal-pvc
  namespace: quantal-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
