##################################################################
#              Docker Compose file that starts Kong              #
##################################################################

# Load Balancing
consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  dns:
    - 127.0.0.1

nginx-lb:
  build: nginx/
  mem_limit: 128m
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
  expose:
    - 8000
    - 8443
    - 8001
  links:
    - consul:consul
  restart: always
  command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"

# Kong Database

#kong-database:
#  image: postgres:9.4
#  ports:
#    - 5432
#  environment:
#    - POSTGRES_USER=kong
#    - POSTGRES_DB=kong

kong-database:
  image: cassandra:2.2
  ports:
    - 9042

# Kong  Postgres

#kong:
#  build: kong/
#  restart: always
#  links:
#    - kong-database:kong-database
#    - consul
#  ports:
#    - 8000
#    - 8443
#    - 8001
#  expose:
#    - 7946
#    - 7946/udp
#  environment:
#    - KONG_DATABASE=postgres
#    - KONG_PG_HOST=kong-database

# Kong using cassandra

kong:
  build: kong/
  restart: always
  links:
    - kong-database:kong-database
    - consul
  ports:
    - 8000
    - 8443
    - 8001
  expose:
    - 7946
    - 7946/udp
  environment:
    - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    - KONG_DATABASE=cassandra

PostgreSQL:
  restart: always
  image: sameersbn/postgresql:9.6-2
  ports:
    - "5432:5432"
  environment:
    - DEBUG=false

    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=postgres
    - PG_PASSWORD=postgres
    - DB_TEMPLATE=

    - DB_EXTENSION=

    - REPLICATION_MODE=
    - REPLICATION_USER=
    - REPLICATION_PASS=
    - REPLICATION_SSLMODE=
#  volumes:
#    - /srv/docker/postgresql:/var/lib/postgresql
  