apiVersion: v1
kind: Service
metadata:
  labels:
    app: busybox
  name: busybox-svc-internal
  namespace: quantal-dev
spec:
  ports:
    - name: busybox-internal
      port: 9092
  selector:
    app: busybox

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: busybox-port-external-svc
  name: busybox-port-external-svc
  namespace: quantal-dev
spec:
  type: NodePort
  ports:
    - name: busybox-external-node-port
      port: 9092
      nodePort: 30011
      protocol: TCP
      targetPort: 30010
  selector:
    app: busybox

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
  namespace: quantal-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      hostname: busybox
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent

