apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-svc-internal
  namespace: quantal-dev
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      nodePort: 30005
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-svc
  namespace: quantal-dev
spec:
  type: NodePort
  ports:
    - name: postgres-default-port
      port: 5432
      nodePort: 30004
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: quantal-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: postgres
      containers:
      - name: postgres
        image: postgres:15.1
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-data-volume
            mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres-data-local-path-pvc
