apiVersion: v1
kind: Service
metadata:
  name: quantal-car-garage-car-parts-svc
  labels:
    app: quantal-car-garage-car-parts
  namespace: quantal-dev
spec:
  selector:
    app: quantal-car-garage-car-parts
  type: NodePort
  ports:
    - name: quantal-car-garage-car-parts-port
      nodePort: 30006
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantal-car-garage-car-parts-deployment
  namespace: quantal-dev
  labels:
    app: quantal-car-garage-car-parts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantal-car-garage-car-parts
  template:
    metadata:
      labels:
        app: quantal-car-garage-car-parts
    spec:
      containers:
      - name: quantal-car-garage-car-parts
        image: quophyie/car-parts:latest
        ports:
        - containerPort: 3000
        env:
          - name: HOST_IP
            value: kafka-svc-internal.quantal-dev
#          - name: KAFKA_PRODUCER_OUTPUT_TOPIC
#            value: car-garage-users
