##################################################################
#              Docker Compose file that starts Kong              #
##################################################################

version: '3.7'
#networks:
#  container_services_networks:
#    driver: bridge
networks:
  default:
    external:
      name: container_services_networks
services:
  # Load Balancing
  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1
    networks:
      - container_services_networks
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "df-customer-bi:1:1,df-customer-errors:1:1,df-customer:1:1,df-customer-client-errors:1:1,df-customer-der:1:1"
      KAFKA_ZOOKEEPER_CONNECT: ${HOST_IP}:2181
    depends_on:
      - zookeeper

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest
    ports:
      - "8082:8082"
    environment:
      - KAFKA_REST_HOST_NAME=kafka-rest-proxy
      - KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    ports:
      - "8200:8000"
    environment:
      #- KAFKA_REST_PROXY_URL=http://localhost:8082
      - KAFKA_REST_PROXY_URL=http://kafka-rest-proxy:8082
      - PROXY=true